task_name: Humanoid          # IsaacGymEnvs의 기본 휴머노이드
seed: 1
num_envs: 4                  # 노트북 GPU 부담 낮게
horizon: 1024                # rollout 길이
mini_batch_size: 2048
update_epochs: 4
gamma: 0.99
gae_lambda: 0.95
clip_coef: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
learning_rate: 3.0e-4
hidden_size: 256
log_interval: 10
eval_interval: 50
total_updates: 2000          # 필요에 맞게 조절

