task_name: Humanoid
num_envs: 2
seed: 1
hidden_size: 256
horizon: 1024
learning_rate: 3e-4
ppo_epoch: 4
num_mini_batch: 4
value_loss_coef: 0.5
entropy_coef: 0.01
total_updates: 100000
log_interval: 10
eval_interval: 50

headless: false
graphics_device_id: 0
render: true
render_interval: 1
cam_follow: true
cam_distance: 2.2   # 작을수록 더 가까움
cam_height: 1.0
cam_yaw_deg: 20.0

wm:
  enabled: true
  ckpt_path: world_model_diffode.pt   # 절대/상대 경로 확인
  dof_dim: 35
  z_dim: 64
  detach_z: false

